### ISSUE TITLE
FAR is the keyword of C language

### ISSUE THREAD

**Issue by walkupup** [wincle/NPD#1]
the variable FAR is the keyword of C language. I compiled it in vs and got errors. 
btw, the training method in the paper is soft cascade , and your implemention is gentle  adaboost? 
is there any testing result?

**Comment by wincle** [comment]
Please wait, the code is not finished.

**Comment by wincle** [comment]
The Training code is finished , but I think there might be some problem that I haven't noticed , welcome to test the code and thank you for your star :)

**Comment by walkupup** [comment]
the memory allocation with "new" has no corresponding "delete" in all of the related functions.

**Comment by wincle** [comment]
Sorry about my code style , thank you for your attention :)
now I have fixed it.
