### ISSUE TITLE
Which training parameters are be modified?

### ISSUE THREAD

**Issue by younger-diao** [wincle/NPD#10]
Hello,my learned model is poor.How many neg images and hard neg images did you use and what is the ration of neg/pos?Which training parameters are be modified for your 620model?Thank you very much!

**Comment by wincle** [comment]
The default parameters are my used. 
There are 20,000 pos images  I prepared for training which generate 200,000 pos samples. And I prepared 50,000 neg images for negative hard samples mining.
Initial neg/pos ration is 1:1 and when neg/pos ration is 0.5:1, start mining.

**Comment by younger-diao** [comment]
Thank you for your answers. I generated pos *negRatio hard neg images for init training.That's right? When neg/pos ration is 0.5:1, start mining means that  is minSamples 100000?

**Comment by wincle** [comment]
That's right.

**Comment by younger-diao** [comment]
OK.Thank you very much!

**Comment by younger-diao** [comment]
There are different processes for training in Windows and Linux using the same samples.And we can find nPos is always dropping in Windows, and nPos is always keeping unchanged in Linux from below. So do you know why? Thanks a lot!
A training process in Windows:
                                             Iter 5:nPos=102205,nNeg=86723
                                             Iter 6:nPos=100441,nNeg=77326
A training process in Linux:
                                             Iter 176:nPos=211820,nNeg=116140
                                             Iter 177:nPos=211820,nNeg=110008

**Comment by wincle** [comment]
I haven't training a model in Windows and nPos shouldn't dropping, check the code in Line:120-133 of LearnGAB.cpp, the nPos is dropping here, debug it and you will find what happened.

**Comment by younger-diao** [comment]
OK. I got it. Thanks a lot!
