### ISSUE TITLE
无法检测出人脸

### ISSUE THREAD

**Issue by smartadpole** [wincle/NPD#16]
框为32时无法检测出人脸；
框为24*24时，Nms函数崩溃：
int numCandidates = rects.size();
Mat predicate = Mat::eye(numCandidates,numCandidates,IPL_DEPTH_1U); //此处宽高超过31000会崩溃
宽高太大，也就是rects数目太多（调试时看到是6位数）

**Comment by smartadpole** [comment]
You must change the code in detection/LearnGAB.cpp:8696. Because the difference between matlab and OpenCV. You should also change the coefficient in detection/LearnGAB.cpp:276279 to fit the model.
能详细说一下吗

**Comment by wincle** [comment]
620的model是从作者的模型dump过来的，由于matlab和opencv的读图顺序不一样，所以模型的load方式也不一样，所以要改一下代码。如果你用我的1226模型，代码不用改，至于你检测不出人脸的问题，看下是不是图片太大（横纵超过1000）而且人脸面积占图片比例很高。

**Comment by smartadpole** [comment]
很感谢您的回复！
1226和620都尝试过；
1.  图片确实比较大1080*1920，这会有什么影响吗？
2.  人脸比例并不大，上述尺寸的图片中有3个人脸左右，而且是远距离；人脸比例会有什么影响吗？
3.  类似的问题，其他还有什么要注意的吗？

**Comment by smartadpole** [comment]
刚刚尝试了一下缩小图像至540*960，依然是同样的问题——
Mat predicate = Mat::eye(numCandidates,numCandidates,IPL_DEPTH_1U); //此处宽高超过31000会崩溃
此处计算出的numCandidates=52000；
我是应该先读论文还是先分析你的代码（因为时间比较紧，所以有优先级）

**Comment by wincle** [comment]
贴一下报的错，直接用代码就行

**Comment by smartadpole** [comment]
报错：OpenCV Error: One of arguments' values is out of range (The total matrix size does not fit to "size_t" type) in setSize, file E:\opencv-2.4.13.2\modules\core\src\matrix.cpp, line 126
就是我上一个回答中的那行代码报的错，图像过大，造成opencv分配内存时直接崩溃

**Comment by wincle** [comment]
numC... 是检测到的人脸框，正常不会超过100

**Comment by smartadpole** [comment]
上一个找到问题原因了，我model路径写错了，导致初始化就不对；
谢谢你！
----------------------新的问题------------------------
1.  Nms是在做矩形框聚合是吗
2. loadModel函数中，读取模型数据 points1 中的数据有问题，导致  pPixel[offset[points1[k][node]]]; 里边的offset越界了
这样的情况下，我得自己去训练数据吗，还是程序哪里出了问题 ；points1 从读取之后就没有过其他操作

**Comment by smartadpole** [comment]
程序中所有的29都是 金字塔层数吗

**Comment by smartadpole** [comment]
我直接运行您的源码，也是崩溃，什么都没改，模型用的1226
