### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by smartadpole** [wincle/NPD#18]
代码中的 feaIds 是做什么用的
`feaIds.push_back(feaId[i]);  
leftChilds.push_back(leftChild[i]);  
rightChilds.push_back(rightChild[i]);  
cutpoints.push_back(cutpoint[i << 1]);`

**Comment by wincle** [comment]
NPD特征ID，我建议你还是看下论文，至少了解NPD特征是什么，boost算法什么原理。

**Comment by smartadpole** [comment]
论文看了，NPD特征知道，boost没看；
feature id 检测过程没有看到使用；

**Comment by smartadpole** [comment]
另一个问题：确实有一段代码看不懂了
金字塔缩放，缩放的是模板还是检测图像

**Comment by wincle** [comment]
缩放的是模板，速度比缩放图像更快。

**Comment by smartadpole** [comment]
谢谢！
已经弄明白了。
