### ISSUE TITLE
about NMS

### ISSUE THREAD

**Issue by frischzenger** [wincle/NPD#4]
opencv function Mat::eye is memory consumptive, when numCandidates is 200k, it will take away 200000*200000=40,000,000,000, nearly 40G memory.

**Comment by frischzenger** [comment]
SparseMat will be better?

**Comment by wincle** [comment]
Thank for your attention , but the numCandidates is the number of the faces detected, it isn't the number of postive samples, the numCandidates usually is lower than 100.
