### ISSUE TITLE
LearnGAB.cpp bug

### ISSUE THREAD

**Issue by caxieyou** [wincle/NPD#5]
LearnGAB.cpp line 276 and 278

```
int y0 = max(rects[idx].y - floor(3.0 * delta),0);

int x0 = max(rects[idx].x + floor(0.25 * delta),0);
```

why the y0 offset is 3 times of delta, but x is only 0.25 times of detla?

shouldn't the 3 become 0.3?

**Comment by wincle** [comment]
Course the face's height is larger than width.
