### ISSUE TITLE
num of negative dataset

### ISSUE THREAD

**Issue by Zouhj** [wincle/NPD#6]
The negRatio is 0.5 means when loadding negative dataset we just load the half size of positive dataset. I used 24142 face images, acturlly 241420 for training,and the loaded neg size is 120710. The nNeg was declining. In LearnGAB.cpp, void GAB::MiningNeg(int n,DataSet& neg), the function can not mine more negs, so the program stucked when I trained 199 stages.
 I am confused that should not negdataset much larger than posdataset generally? I tried to change the negRatio to 2 or 3 to load more negs, but run error. what's wrong?

**Comment by wincle** [comment]
In common.cpp , you should notice minSamples decides when to do mining.
you should delete the model first and change the negRatio to retrain , Because the default is continue the training with that existing model with negRatio of 0.5.

**Comment by wincle** [comment]
You are right , I get the error, I will fix the bug soon.

**Comment by Zouhj** [comment]
yeah,I noticed that. minSample is 20000, when nNeg is smaller than minSample, go MiningNeg. I also deleted the model and then change the Ratio to train again.
okay, thank you so much to solve the error！

**Comment by wincle** [comment]
fix by last commit.
Did that help you?

**Comment by Zouhj** [comment]
Yeah,I got it! Thank you so much, I am trainning now
