### ISSUE TITLE
coefficients by using matlab model

### ISSUE THREAD

**Issue by ChrisYang** [wincle/NPD#7]
As you mentioned 'Because the difference between matlab and OpenCV. You should also change the coefficient in detection/LearnGAB.cpp:276~279 to fit the model.' , if I keep the parameters as they are, i get a bit strange outputs.  Do you have any hints how to set those parameters if I want to use the model trained from Matlab? Thanks.

**Comment by wincle** [comment]
```
    r0 = max(rects{i}(j).row - floor(2.5 * delta), 1);
    r1 = min(rects{i}(j).row + rects{i}(j).size - 1 + floor(2.5 * delta), imgHeight);
    c0 = max(rects{i}(j).col - delta, 1);
    c1 = min(rects{i}(j).col + rects{i}(j).size - 1 + delta, imgWidth);
```
